
// This file was auto-generated by ML.NET Model Builder. 

using FootballResultModel_PremierLeagueEN;

// Create single instance of sample data from first line of dataset for model input
FootballResultModel.ModelInput sampleData = new FootballResultModel.ModelInput()
{
    Div = @"E0",
    Date = @"01/05/2023",
    Time = @"20:00",
    HomeTeam = @"Wolves",
    AwayTeam = @"Man United",
    //FTHG = 2F,
    //FTAG = 2F,
    //HTHG = 1F,
    //HTAG = 0F,
    //HTR = @"H",
    Referee = @"P Tierney",
    //HS = 9F,
    //AS = 11F,
    //HST = 3F,
    //AST = 4F,
    //HF = 7F,
    //AF = 9F,
    //HC = 4F,
    //AC = 4F,
    //HY = 2F,
    //AY = 0F,
    //HR = 0F,
    //AR = 0F,
   // B365H = 5F,
    //B365D = 4F,
   // B365A = 1.62F
    //BWH = 10F,
    //IWH = 12F,
    //WHH = 12F,
    //VCH = 13F,
    //VCD = 6F,
    //MaxH = 13F,
    //PAHA = 2F,
    //B365CH = 11F,
    //BWCD = 6F,
    //IWCH = 11F,
    //WHCH = 11F,
    //VCCD = 6F,
    //MaxC_2_5 = 3F,
};

var predictionResult = FootballResultModel.Predict(sampleData);

var roundedResult = Math.Round(predictionResult.Score, 0);
Console.WriteLine($"\nPredicted FTR: {predictionResult.Score} (Ronded FTR: {roundedResult})\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

