
// This file was auto-generated by ML.NET Model Builder. 

using FootballResultModel_PremierLeagueEN;

// Create single instance of sample data from first line of dataset for model input
//Load sample data
var sampleData = new FootballResultModel.ModelInput()
{
    //Match_Number = 2F,
    //Round_Number = 1F,
    Date = @"13/01/2023 20:00",
    Location = @"Villa Park",
    Home_Team = @"Aston Villa",
    Away_Team = @"Leeds",
    //Result = @"2 - 2",
    //AG = 2F,
};

//Load model and predict output
var result = FootballResultModel.Predict(sampleData);


var roundedResult = Math.Round(result.Score, 0);
Console.WriteLine(roundedResult);
//Console.WriteLine($"\nPredicted FTR: {result.Score} (Ronded FTR: {roundedResult})\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

