@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ikdlb3JnZXMiLCJzdWIiOiJHZW9yZ2VzIiwianRpIjoiY2Y1MWVkODIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDoyNzI3MSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzEyIiwiaHR0cDovL2xvY2FsaG9zdDo1MTYzIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzE3NyJdLCJuYmYiOjE3MTg0ODM5NTEsImV4cCI6MTcyNjQzMjc1MSwiaWF0IjoxNzE4NDgzOTUyLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.okP8bFjc3fx3JjBfxhdTmnkaFMnGmPmaASIoemdwFdQ
### Hello

GET http://localhost:5163/hello
Authorization: Bearer {{AccessToken}}