// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace PL_champion_2023
{
    public partial class PL_CHAMPION_2023
    {
        /// <summary>
        /// model input class for PL_CHAMPION_2023.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Season")]
            public string Season { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Pos")]
            public float Pos { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Team")]
            public string Team { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Pld")]
            public float Pld { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"W")]
            public float W { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"D")]
            public float D { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"L")]
            public float L { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"GF")]
            public float GF { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"GA")]
            public float GA { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"GD")]
            public float GD { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Pts")]
            public float Pts { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PL_CHAMPION_2023.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Season")]
            public float[] Season { get; set; }

            [ColumnName(@"Pos")]
            public float Pos { get; set; }

            [ColumnName(@"Team")]
            public float[] Team { get; set; }

            [ColumnName(@"Pld")]
            public float Pld { get; set; }

            [ColumnName(@"W")]
            public float W { get; set; }

            [ColumnName(@"D")]
            public float D { get; set; }

            [ColumnName(@"L")]
            public float L { get; set; }

            [ColumnName(@"GF")]
            public float GF { get; set; }

            [ColumnName(@"GA")]
            public float GA { get; set; }

            [ColumnName(@"GD")]
            public float GD { get; set; }

            [ColumnName(@"Pts")]
            public float Pts { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PL-CHAMPION-2023.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
