// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Football_Matches_Predictor
{
    public partial class MatchModelmbconfig
    {
        /// <summary>
        /// model input class for MatchModelmbconfig.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Div")]
            public string Div { get; set; }

            [ColumnName(@"Date")]
            public string Date { get; set; }

            [ColumnName(@"Time")]
            public string Time { get; set; }

            [ColumnName(@"HomeTeam")]
            public string HomeTeam { get; set; }

            [ColumnName(@"AwayTeam")]
            public string AwayTeam { get; set; }

            [ColumnName(@"FTHG")]
            public float FTHG { get; set; }

            [ColumnName(@"FTAG")]
            public float FTAG { get; set; }

            [ColumnName(@"FTR")]
            public string FTR { get; set; }

            [ColumnName(@"HTHG")]
            public float HTHG { get; set; }

            [ColumnName(@"HTAG")]
            public float HTAG { get; set; }

            [ColumnName(@"HTR")]
            public string HTR { get; set; }

            [ColumnName(@"HS")]
            public float HS { get; set; }

            [ColumnName(@"AS")]
            public float AS { get; set; }

            [ColumnName(@"HST")]
            public float HST { get; set; }

            [ColumnName(@"AST")]
            public float AST { get; set; }

            [ColumnName(@"HF")]
            public float HF { get; set; }

            [ColumnName(@"AF")]
            public float AF { get; set; }

            [ColumnName(@"HC")]
            public float HC { get; set; }

            [ColumnName(@"AC")]
            public float AC { get; set; }

            [ColumnName(@"HY")]
            public float HY { get; set; }

            [ColumnName(@"AY")]
            public float AY { get; set; }

            [ColumnName(@"HR")]
            public float HR { get; set; }

            [ColumnName(@"AR")]
            public float AR { get; set; }

            [ColumnName(@"B365H")]
            public float B365H { get; set; }

            [ColumnName(@"B365D")]
            public float B365D { get; set; }

            [ColumnName(@"B365A")]
            public float B365A { get; set; }

            [ColumnName(@"BWH")]
            public float BWH { get; set; }

            [ColumnName(@"BWD")]
            public float BWD { get; set; }

            [ColumnName(@"BWA")]
            public float BWA { get; set; }

            [ColumnName(@"IWH")]
            public float IWH { get; set; }

            [ColumnName(@"IWD")]
            public float IWD { get; set; }

            [ColumnName(@"IWA")]
            public float IWA { get; set; }

            [ColumnName(@"PSH")]
            public float PSH { get; set; }

            [ColumnName(@"PSD")]
            public float PSD { get; set; }

            [ColumnName(@"PSA")]
            public float PSA { get; set; }

            [ColumnName(@"WHH")]
            public float WHH { get; set; }

            [ColumnName(@"WHD")]
            public float WHD { get; set; }

            [ColumnName(@"WHA")]
            public float WHA { get; set; }

            [ColumnName(@"VCH")]
            public float VCH { get; set; }

            [ColumnName(@"VCD")]
            public float VCD { get; set; }

            [ColumnName(@"VCA")]
            public float VCA { get; set; }

            [ColumnName(@"MaxH")]
            public float MaxH { get; set; }

            [ColumnName(@"MaxD")]
            public float MaxD { get; set; }

            [ColumnName(@"MaxA")]
            public float MaxA { get; set; }

            [ColumnName(@"AvgH")]
            public float AvgH { get; set; }

            [ColumnName(@"AvgD")]
            public float AvgD { get; set; }

            [ColumnName(@"AvgA")]
            public float AvgA { get; set; }

            [ColumnName(@"B365>2.5")]
            public float B365_2_5 { get; set; }

            [ColumnName(@"B365<2.5")]
            public float B365_2_5 { get; set; }

            [ColumnName(@"P>2.5")]
            public float P_2_5 { get; set; }

            [ColumnName(@"P<2.5")]
            public float P_2_5 { get; set; }

            [ColumnName(@"Max>2.5")]
            public float Max_2_5 { get; set; }

            [ColumnName(@"Max<2.5")]
            public float Max_2_5 { get; set; }

            [ColumnName(@"Avg>2.5")]
            public float Avg_2_5 { get; set; }

            [ColumnName(@"Avg<2.5")]
            public float Avg_2_5 { get; set; }

            [ColumnName(@"AHh")]
            public float AHh { get; set; }

            [ColumnName(@"B365AHH")]
            public float B365AHH { get; set; }

            [ColumnName(@"B365AHA")]
            public float B365AHA { get; set; }

            [ColumnName(@"PAHH")]
            public float PAHH { get; set; }

            [ColumnName(@"PAHA")]
            public float PAHA { get; set; }

            [ColumnName(@"MaxAHH")]
            public float MaxAHH { get; set; }

            [ColumnName(@"MaxAHA")]
            public float MaxAHA { get; set; }

            [ColumnName(@"AvgAHH")]
            public float AvgAHH { get; set; }

            [ColumnName(@"AvgAHA")]
            public float AvgAHA { get; set; }

            [ColumnName(@"B365CH")]
            public float B365CH { get; set; }

            [ColumnName(@"B365CD")]
            public float B365CD { get; set; }

            [ColumnName(@"B365CA")]
            public float B365CA { get; set; }

            [ColumnName(@"BWCH")]
            public float BWCH { get; set; }

            [ColumnName(@"BWCD")]
            public float BWCD { get; set; }

            [ColumnName(@"BWCA")]
            public float BWCA { get; set; }

            [ColumnName(@"IWCH")]
            public float IWCH { get; set; }

            [ColumnName(@"IWCD")]
            public float IWCD { get; set; }

            [ColumnName(@"IWCA")]
            public float IWCA { get; set; }

            [ColumnName(@"PSCH")]
            public float PSCH { get; set; }

            [ColumnName(@"PSCD")]
            public float PSCD { get; set; }

            [ColumnName(@"PSCA")]
            public float PSCA { get; set; }

            [ColumnName(@"WHCH")]
            public float WHCH { get; set; }

            [ColumnName(@"WHCD")]
            public float WHCD { get; set; }

            [ColumnName(@"WHCA")]
            public float WHCA { get; set; }

            [ColumnName(@"VCCH")]
            public float VCCH { get; set; }

            [ColumnName(@"VCCD")]
            public float VCCD { get; set; }

            [ColumnName(@"VCCA")]
            public float VCCA { get; set; }

            [ColumnName(@"MaxCH")]
            public float MaxCH { get; set; }

            [ColumnName(@"MaxCD")]
            public float MaxCD { get; set; }

            [ColumnName(@"MaxCA")]
            public float MaxCA { get; set; }

            [ColumnName(@"AvgCH")]
            public float AvgCH { get; set; }

            [ColumnName(@"AvgCD")]
            public float AvgCD { get; set; }

            [ColumnName(@"AvgCA")]
            public float AvgCA { get; set; }

            [ColumnName(@"B365C>2.5")]
            public float B365C_2_5 { get; set; }

            [ColumnName(@"B365C<2.5")]
            public float B365C_2_5 { get; set; }

            [ColumnName(@"PC>2.5")]
            public float PC_2_5 { get; set; }

            [ColumnName(@"PC<2.5")]
            public float PC_2_5 { get; set; }

            [ColumnName(@"MaxC>2.5")]
            public float MaxC_2_5 { get; set; }

            [ColumnName(@"MaxC<2.5")]
            public float MaxC_2_5 { get; set; }

            [ColumnName(@"AvgC>2.5")]
            public float AvgC_2_5 { get; set; }

            [ColumnName(@"AvgC<2.5")]
            public float AvgC_2_5 { get; set; }

            [ColumnName(@"AHCh")]
            public float AHCh { get; set; }

            [ColumnName(@"B365CAHH")]
            public float B365CAHH { get; set; }

            [ColumnName(@"B365CAHA")]
            public float B365CAHA { get; set; }

            [ColumnName(@"PCAHH")]
            public float PCAHH { get; set; }

            [ColumnName(@"PCAHA")]
            public float PCAHA { get; set; }

            [ColumnName(@"MaxCAHH")]
            public float MaxCAHH { get; set; }

            [ColumnName(@"MaxCAHA")]
            public float MaxCAHA { get; set; }

            [ColumnName(@"AvgCAHH")]
            public float AvgCAHH { get; set; }

            [ColumnName(@"AvgCAHA")]
            public float AvgCAHA { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MatchModelmbconfig.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Div")]
            public float[] Div { get; set; }

            [ColumnName(@"Date")]
            public float[] Date { get; set; }

            [ColumnName(@"Time")]
            public float[] Time { get; set; }

            [ColumnName(@"HomeTeam")]
            public float[] HomeTeam { get; set; }

            [ColumnName(@"AwayTeam")]
            public float[] AwayTeam { get; set; }

            [ColumnName(@"FTHG")]
            public float FTHG { get; set; }

            [ColumnName(@"FTAG")]
            public float FTAG { get; set; }

            [ColumnName(@"FTR")]
            public float[] FTR { get; set; }

            [ColumnName(@"HTHG")]
            public float HTHG { get; set; }

            [ColumnName(@"HTAG")]
            public float HTAG { get; set; }

            [ColumnName(@"HTR")]
            public float[] HTR { get; set; }

            [ColumnName(@"HS")]
            public float HS { get; set; }

            [ColumnName(@"AS")]
            public float AS { get; set; }

            [ColumnName(@"HST")]
            public float HST { get; set; }

            [ColumnName(@"AST")]
            public float AST { get; set; }

            [ColumnName(@"HF")]
            public float HF { get; set; }

            [ColumnName(@"AF")]
            public float AF { get; set; }

            [ColumnName(@"HC")]
            public float HC { get; set; }

            [ColumnName(@"AC")]
            public float AC { get; set; }

            [ColumnName(@"HY")]
            public float HY { get; set; }

            [ColumnName(@"AY")]
            public float AY { get; set; }

            [ColumnName(@"HR")]
            public float HR { get; set; }

            [ColumnName(@"AR")]
            public float AR { get; set; }

            [ColumnName(@"B365H")]
            public float B365H { get; set; }

            [ColumnName(@"B365D")]
            public float B365D { get; set; }

            [ColumnName(@"B365A")]
            public float B365A { get; set; }

            [ColumnName(@"BWH")]
            public float BWH { get; set; }

            [ColumnName(@"BWD")]
            public float BWD { get; set; }

            [ColumnName(@"BWA")]
            public float BWA { get; set; }

            [ColumnName(@"IWH")]
            public float IWH { get; set; }

            [ColumnName(@"IWD")]
            public float IWD { get; set; }

            [ColumnName(@"IWA")]
            public float IWA { get; set; }

            [ColumnName(@"PSH")]
            public float PSH { get; set; }

            [ColumnName(@"PSD")]
            public float PSD { get; set; }

            [ColumnName(@"PSA")]
            public float PSA { get; set; }

            [ColumnName(@"WHH")]
            public float WHH { get; set; }

            [ColumnName(@"WHD")]
            public float WHD { get; set; }

            [ColumnName(@"WHA")]
            public float WHA { get; set; }

            [ColumnName(@"VCH")]
            public float VCH { get; set; }

            [ColumnName(@"VCD")]
            public float VCD { get; set; }

            [ColumnName(@"VCA")]
            public float VCA { get; set; }

            [ColumnName(@"MaxH")]
            public float MaxH { get; set; }

            [ColumnName(@"MaxD")]
            public float MaxD { get; set; }

            [ColumnName(@"MaxA")]
            public float MaxA { get; set; }

            [ColumnName(@"AvgH")]
            public float AvgH { get; set; }

            [ColumnName(@"AvgD")]
            public float AvgD { get; set; }

            [ColumnName(@"AvgA")]
            public float AvgA { get; set; }

            [ColumnName(@"B365>2.5")]
            public float B365_2_5 { get; set; }

            [ColumnName(@"B365<2.5")]
            public float B365_2_5 { get; set; }

            [ColumnName(@"P>2.5")]
            public float P_2_5 { get; set; }

            [ColumnName(@"P<2.5")]
            public float P_2_5 { get; set; }

            [ColumnName(@"Max>2.5")]
            public float Max_2_5 { get; set; }

            [ColumnName(@"Max<2.5")]
            public float Max_2_5 { get; set; }

            [ColumnName(@"Avg>2.5")]
            public float Avg_2_5 { get; set; }

            [ColumnName(@"Avg<2.5")]
            public float Avg_2_5 { get; set; }

            [ColumnName(@"AHh")]
            public float AHh { get; set; }

            [ColumnName(@"B365AHH")]
            public float B365AHH { get; set; }

            [ColumnName(@"B365AHA")]
            public float B365AHA { get; set; }

            [ColumnName(@"PAHH")]
            public float PAHH { get; set; }

            [ColumnName(@"PAHA")]
            public float PAHA { get; set; }

            [ColumnName(@"MaxAHH")]
            public float MaxAHH { get; set; }

            [ColumnName(@"MaxAHA")]
            public float MaxAHA { get; set; }

            [ColumnName(@"AvgAHH")]
            public float AvgAHH { get; set; }

            [ColumnName(@"AvgAHA")]
            public float AvgAHA { get; set; }

            [ColumnName(@"B365CH")]
            public float B365CH { get; set; }

            [ColumnName(@"B365CD")]
            public float B365CD { get; set; }

            [ColumnName(@"B365CA")]
            public float B365CA { get; set; }

            [ColumnName(@"BWCH")]
            public float BWCH { get; set; }

            [ColumnName(@"BWCD")]
            public float BWCD { get; set; }

            [ColumnName(@"BWCA")]
            public float BWCA { get; set; }

            [ColumnName(@"IWCH")]
            public float IWCH { get; set; }

            [ColumnName(@"IWCD")]
            public float IWCD { get; set; }

            [ColumnName(@"IWCA")]
            public float IWCA { get; set; }

            [ColumnName(@"PSCH")]
            public float PSCH { get; set; }

            [ColumnName(@"PSCD")]
            public float PSCD { get; set; }

            [ColumnName(@"PSCA")]
            public float PSCA { get; set; }

            [ColumnName(@"WHCH")]
            public float WHCH { get; set; }

            [ColumnName(@"WHCD")]
            public float WHCD { get; set; }

            [ColumnName(@"WHCA")]
            public float WHCA { get; set; }

            [ColumnName(@"VCCH")]
            public float VCCH { get; set; }

            [ColumnName(@"VCCD")]
            public float VCCD { get; set; }

            [ColumnName(@"VCCA")]
            public float VCCA { get; set; }

            [ColumnName(@"MaxCH")]
            public float MaxCH { get; set; }

            [ColumnName(@"MaxCD")]
            public float MaxCD { get; set; }

            [ColumnName(@"MaxCA")]
            public float MaxCA { get; set; }

            [ColumnName(@"AvgCH")]
            public float AvgCH { get; set; }

            [ColumnName(@"AvgCD")]
            public float AvgCD { get; set; }

            [ColumnName(@"AvgCA")]
            public float AvgCA { get; set; }

            [ColumnName(@"B365C>2.5")]
            public float B365C_2_5 { get; set; }

            [ColumnName(@"B365C<2.5")]
            public float B365C_2_5 { get; set; }

            [ColumnName(@"PC>2.5")]
            public float PC_2_5 { get; set; }

            [ColumnName(@"PC<2.5")]
            public float PC_2_5 { get; set; }

            [ColumnName(@"MaxC>2.5")]
            public float MaxC_2_5 { get; set; }

            [ColumnName(@"MaxC<2.5")]
            public float MaxC_2_5 { get; set; }

            [ColumnName(@"AvgC>2.5")]
            public float AvgC_2_5 { get; set; }

            [ColumnName(@"AvgC<2.5")]
            public float AvgC_2_5 { get; set; }

            [ColumnName(@"AHCh")]
            public float AHCh { get; set; }

            [ColumnName(@"B365CAHH")]
            public float B365CAHH { get; set; }

            [ColumnName(@"B365CAHA")]
            public float B365CAHA { get; set; }

            [ColumnName(@"PCAHH")]
            public float PCAHH { get; set; }

            [ColumnName(@"PCAHA")]
            public float PCAHA { get; set; }

            [ColumnName(@"MaxCAHH")]
            public float MaxCAHH { get; set; }

            [ColumnName(@"MaxCAHA")]
            public float MaxCAHA { get; set; }

            [ColumnName(@"AvgCAHH")]
            public float AvgCAHH { get; set; }

            [ColumnName(@"AvgCAHA")]
            public float AvgCAHA { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MatchModelmbconfig.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
