
// This file was auto-generated by ML.NET Model Builder. 

using CommentsModel_PositiveOrNegative;

// Create single instance of sample data from first line of dataset for model input
FootballResultModel.ModelInput sampleData = new FootballResultModel.ModelInput()
{
    Col0 = "This is my loved place.",
};

// Make a single prediction on the sample data and print results
var predictionResult = FootballResultModel.Predict(sampleData);

var sentiment = predictionResult.PredictedLabel == 1 ? "Positive" : "Negative";
Console.WriteLine($"Text: {sampleData.Col0}\nSentiment: {sentiment}");

